/* ORDER BY */
/* ORDER BY절은 SELECT문과 함께 사용하며 결과 집합을 특정 열이나
   열들의 값에 따라 정렬하는 데 사용한다.
*/
SELECT
       MENU_CODE
	 , MENU_NAME
     , MENU_PRICE
  FROM TBL_MENU
-- ORDER BY MENU_PRICE
 ORDER BY MENU_PRICE ASC;
 
SELECT 
       MENU_CODE
     , MENU_NAME
     , MENU_PRICE
  FROM TBL_MENU
 ORDER BY MENU_PRICE DESC; 
 
SELECT 
       MENU_CODE
     , MENU_NAME
     , MENU_PRICE
  FROM TBL_MENU
 ORDER BY MENU_PRICE DESC,
	      MENU_NAME ASC;
          
SELECT
       MENU_CODE
     , MENU_NAME
     , MENU_PRICE * MENU_CODE
  FROM TBL_MENU
 ORDER BY MENU_PRICE * MENU_CODE DESC;
 
SELECT 
       FIELD(ORDERABLE_STATUS, 'Y', 'N')
  FROM TBL_MENU;
  
SELECT
       MENU_NAME
     , ORDERABLE_STATUS
  FROM TBL_MENU
 ORDER BY FIELD(ORDERABLE_STATUS, 'N', 'Y'); 
 
-- 오름차순 시 NULL 처음으로
SELECT
       CATEGORY_CODE
     , CATEGORY_NAME
     , REF_CATEGORY_CODE
  FROM TBL_CATEGORY
 ORDER BY REF_CATEGORY_CODE;
 
-- 오름차순 시 NULL 마지막으로
SELECT
       CATEGORY_CODE
     , CATEGORY_NAME
     , REF_CATEGORY_CODE
  FROM TBL_CATEGORY
 ORDER BY REF_CATEGORY_CODE IS NULL;
 
-- 내림차순 시 NULL 마지막으로
SELECT
       CATEGORY_CODE
     , CATEGORY_NAME
     , REF_CATEGORY_CODE
  FROM TBL_CATEGORY
 ORDER BY REF_CATEGORY_CODE DESC; 
 
-- 내림차순 시 NULL 처음으로
SELECT
       CATEGORY_CODE
     , CATEGORY_NAME
     , REF_CATEGORY_CODE
  FROM TBL_CATEGORY
 ORDER BY REF_CATEGORY_CODE IS NULL DESC, REF_CATEGORY_CODE DESC;