/* WHERE */
/* WHERE절은 특정 조건에 맞는 레코드만을 선택하는데 사용되며 다양한 방법으로 조건을 설정할 수 있다. */

-- 1) 비교 연산자 예제와 함께 WHERE절 사용
SELECT
       MENU_NAME
     , MENU_PRICE
     , ORDERABLE_STATUS
  FROM TBL_MENU
 WHERE ORDERABLE_STATUS = 'Y';
 
SELECT
       MENU_NAME
     , MENU_PRICE
     , ORDERABLE_STATUS
  FROM TBL_MENU
 WHERE MENU_PRICE = 13000;
 
-- 같지 않음 연산자와 함께 WHERE절 사용 
SELECT
       MENU_CODE
     , MENU_NAME
     , ORDERABLE_STATUS
  FROM TBL_MENU
 WHERE ORDERABLE_STATUS != 'Y';
 
-- 대소 비교 연산자와 함께 WHERE절 사용
SELECT
       MENU_CODE
     , MENU_NAME
     , MENU_PRICE
  FROM TBL_MENU
 WHERE MENU_PRICE > 20000;
 
SELECT
       MENU_CODE
     , MENU_NAME
     , MENU_PRICE
  FROM TBL_MENU
 WHERE MENU_PRICE <= 20000;
 
-- 2) AND연산자와 함께 WHERE절 사용
SELECT
       MENU_NAME
     , MENU_PRICE
     , CATEGORY_CODE
     , ORDERABLE_STATUS
  FROM TBL_MENU
 WHERE ORDERABLE_STATUS = 'Y'
   AND CATEGORY_CODE = 10;
   
-- 메뉴이름, 메뉴가격, 카테고리 코드, 판매상태를 조회하는데,
-- 메뉴가격이 5000원 초과이고 카테고리 코드가 10번인것을 조회하시오.
SELECT
       MENU_NAME
     , MENU_PRICE
     , CATEGORY_CODE
     , ORDERABLE_STATUS
  FROM TBL_MENU
 WHERE MENU_PRICE > 5000
   AND CATEGORY_CODE = 10;
   
-- 03) OR 연산자와 함께 WHERE절 사용
SELECT
       MENU_NAME
     , MENU_PRICE
     , CATEGORY_CODE
     , ORDERABLE_STATUS
  FROM TBL_MENU
 WHERE ORDERABLE_STATUS= 'Y'
    OR CATEGORY_CODE = 10
 ORDER BY CATEGORY_CODE;
 
SELECT
       MENU_NAME
     , MENU_PRICE
     , CATEGORY_CODE
     , ORDERABLE_STATUS
  FROM TBL_MENU
 WHERE MENU_PRICE > 5000
    OR CATEGORY_CODE = 10;
    
-- 메뉴 코드, 메뉴 이름, 메뉴 가격, 카테고리 코드, 판매상태를 조회하는데
-- 카테고리 코드가 4번이거나 메뉴 가격이 9000원이면서 메뉴코드가 10번 초과인 것을 조회하시오.
SELECT
       MENU_CODE
	 , MENU_NAME
     , MENU_PRICE
     , CATEGORY_CODE
     , ORDERABLE_STATUS
  FROM TBL_MENU
 WHERE CATEGORY_CODE = 4
    OR MENU_PRICE = 9000
   AND MENU_CODE > 10; 
   
-- 4) BETWEEN 연산자 예제와 함께 WHERE절 사용
SELECT 
       MENU_NAME
     , MENU_PRICE
     , CATEGORY_CODE
  FROM TBL_MENU
 WHERE MENU_PRICE >= 10000
   AND MENU_PRICE <= 25000
 ORDER BY MENU_PRICE;  
 
SELECT 
       MENU_NAME
     , MENU_PRICE
     , CATEGORY_CODE
  FROM TBL_MENU
 WHERE MENU_PRICE BETWEEN 10000 AND 25000
 ORDER BY MENU_PRICE;
 
-- 부정 표현
SELECT 
       MENU_NAME
     , MENU_PRICE
     , CATEGORY_CODE
  FROM TBL_MENU
 WHERE MENU_PRICE NOT BETWEEN 10000 AND 25000
 ORDER BY MENU_PRICE;
 
-- 5) LIKE 연산자 예제와 함께 WHERE절 사용
SELECT
       MENU_NAME
     , MENU_PRICE
  FROM TBL_MENU
 WHERE MENU_NAME LIKE '%마늘%'
 ORDER BY MENU_NAME;
 
-- 메뉴 코드, 메뉴 이름, 메뉴 가격, 카테고리 코드, 판매상태를 조회하는데
-- 메뉴 가격이 5000 초과이면서 카테고리코드가 10번이면서
-- 메뉴 이름이 갈치가 포함된 메뉴를 조회하시오.
SELECT
       MENU_CODE
     , MENU_NAME
     , MENU_PRICE
     , CATEGORY_CODE
     , ORDERABLE_STATUS
  FROM TBL_MENU    
 WHERE MENU_PRICE > 5000
   AND CATEGORY_CODE = 10
   AND MENU_NAME LIKE '%갈치%';
   
-- 부정 표현
SELECT
       MENU_NAME
     , MENU_PRICE
  FROM TBL_MENU
 WHERE MENU_NAME NOT LIKE '%마늘%'
 ORDER BY MENU_NAME;
 
-- 6) IN 연산자 예제와 함께 WHERE절 사용
SELECT
       MENU_NAME
     , CATEGORY_CODE
  FROM TBL_MENU
 WHERE CATEGORY_CODE = 4
    OR CATEGORY_CODE = 5
    OR CATEGORY_CODE = 6
 ORDER BY CATEGORY_CODE;   
 
SELECT
       MENU_NAME
     , CATEGORY_CODE
  FROM TBL_MENU
 WHERE CATEGORY_CODE IN (4,5,6)
 ORDER BY CATEGORY_CODE;
 
-- 부정 표현 
SELECT
       MENU_NAME
     , CATEGORY_CODE
  FROM TBL_MENU
 WHERE CATEGORY_CODE NOT IN (4,5,6)
 ORDER BY CATEGORY_CODE; 
 
-- 7) IS NULL 연산자와 함께 WHERE절 사용
SELECT
       CATEGORY_CODE
     , CATEGORY_NAME
     , REF_CATEGORY_CODE
  FROM TBL_CATEGORY
 WHERE REF_CATEGORY_CODE IS NULL; 

-- 부정 표현 
SELECT
       CATEGORY_CODE
     , CATEGORY_NAME
     , REF_CATEGORY_CODE
  FROM TBL_CATEGORY
 WHERE REF_CATEGORY_CODE IS NOT NULL;  